function Jw_ee = get_Jw_ee(in1)
%get_Jw_ee
%    Jw_ee = get_Jw_ee(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    18-Apr-2025 14:36:53

Jw_ee = reshape([0.0,-1.0,0.0,0.0,-1.0,0.0],[3,2]);
