function out1 = get_X_ee(in1)
%get_X_ee
%    OUT1 = get_X_ee(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    18-Apr-2025 14:36:53

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
out1 = [cos(q1)+cos(t2);0.0;sin(q1)+sin(t2)];
