function Jv_ee = get_Jv_ee(in1)
%get_Jv_ee
%    Jv_ee = get_Jv_ee(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    18-Apr-2025 14:36:53

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = -t4;
Jv_ee = reshape([t5-sin(q1),0.0,t3+cos(q1),t5,0.0,t3],[3,2]);
