function g_sym = get_g(in1)
%GET_G
%    G_SYM = GET_G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    18-Apr-2025 14:36:53

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = t3.*1.536790628355012e+2;
t5 = -t4;
g_sym = [t5-cos(q1).*4.610371885065037e+2;t5];
