function M_sym = get_M(in1)
%get_M
%    M_sym = get_M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    18-Apr-2025 14:36:53

q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = q1+q2;
t5 = cos(t4);
t6 = sin(t4);
t7 = t5./2.0;
t8 = t6./2.0;
t9 = t2+t7;
t10 = t3+t8;
t11 = t6.*t10.*pi.*1.485e-2;
t12 = t5.*t9.*pi.*5.0135;
t13 = t11+t12+2.625274518966189;
M_sym = reshape([t2.^2.*pi.*2.50675+t3.^2.*pi.*7.425e-3+t9.^2.*pi.*1.0027e+1+t10.^2.*pi.*2.97e-2+5.250549037932378,t13,t13,t5.^2.*pi.*2.50675+t6.^2.*pi.*7.425e-3+2.625274518966189],[2,2]);
