function D_sym = get_D(in1)
%get_D
%    D_sym = get_D(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    18-Apr-2025 14:36:53

D_sym = reshape([1.0./2.0,0.0,0.0,1.0./2.0],[2,2]);
